export const GET_CHESSPLAYER_START = "CHESS::GET_CHESSPLAYER_START";
export const GET_CHESSPLAYER_SUCCESS = "CHESS::GET_CHESSPLAYER_SUCCESS";
export const GET_CHESSPLAYER_ERROR = "CHESS::GET_CHESSPLAYER_ERROR";
